name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build application
        run: |
          echo "Building calculator application..."
          # Exemple de commande fictive pour la construction de la calculatrice
          mkdir build
          touch build/calculator.py

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run automated tests with pytest
        run: |
          pytest -v


  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [test] # Ce job dépend du job 'test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to production
        run: |
          echo "Deploying calculator application to production environment..."
          # Exemple de commande fictive pour le déploiement de l'application de calculatrice
          scp build/calculator.py user@production-server:/var/www/calculator

